### ISSUE TITLE
Enable Neos 5

### ISSUE THREAD

**Issue by rr-appadaptive** [code-q-web-factory/neos-unicodenormalizer#1]
I tried - successfully - to install Neos from scratch yesterday. The installation of a skeleton-site as recommended by the neos-team did not work though because the necessary helper-package codeq/unicodenormalizer cannot be installed for Neos 5.0

**Comment by rolandschuetz** [comment]
Yeah, the release is pretty new. Will update the package today!

**Comment by rolandschuetz** [comment]
Done: https://github.com/code-q-web-factory/neos-unicodenormalizer/releases/tag/v2.2.0
